17.3. Task: entity relations
Patryk241194/Project-kodilla-course-module-6-7 pull request #3
Opened 2023-07-10 20:58 UTC by Patryk241194

Please review the task from submodule 17.3.

2023-07-11 17:41 UTC, hacker-msl requested changes

2023-07-11 17:41 UTC, coder-msl commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/invoice/Item.java
> +    private BigDecimal value;
na pewno chcesz to zapisywać w bazie? To jest pole wyliczalne i jego trzymanie w bazie jest poniekąd nadmiarowe... poza tym ta cena to netto czy brutto?

2023-07-12 20:10 UTC, Patryk241194 commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/invoice/Item.java
> +        return price.multiply(BigDecimal.valueOf(quantity));
Propozycja mojego rozwiązania jeśli chodzi o niezapisywanie w bazie (pełna zmiana w commicie).

W kwestii netto/brutto - nie wiem czy dobrze rozumiem, bo na potrzeby zadania z samego polecenia wydaje się to nieistotne, ale zaznaczyłem, że tu operujemy na netValue.

2023-07-13 16:22 UTC, hacker-msl requested changes

2023-07-13 16:22 UTC, hacker-msl commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/invoice/Item.java
> +        return price.multiply(BigDecimal.valueOf(quantity));
ok, zrób to zgodnie z treścią zadania. Zrób po prostu pole value, które będzie zapisywane (nie będzie dynamicznie wyliczane w getterze).

2023-07-13 17:30 UTC, closed without merging